language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

sudo:     true

addons:
  mariadb: '10.2'

before_install:
  - mysql --version
  - mysql -u root < test/ddl/0010_create_database.sql
  - mysql -u root < test/ddl/0020_create_user.sql
  - mysql -u root test < test/ddl/0100_create_tables.sql
  - mysql -u root test < lib/ddl/0100_create_tables.sql
  - mysql -u root test < test/ddl/0300_abc_lock_named.sql
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"

install:
  - composer self-update
  - composer update
  - ./bin/stratum stratum test/etc/stratum.cfg

script:
  - ./bin/phing unit
