/**
 * Selects the name of a named lock.
 *
 * @param p_cmp_id The ID of the company (safeguard).
 * @param p_lnm_id The ID of the named lock.
 */
create procedure abc_lock_named_get_name(in p_cmp_id @abc_lock_named.cmp_id%type@,
                                         in p_lnm_id @abc_lock_named.lnm_id%type@)
modifies sql data
-- type: singleton1
begin
  select lnm_name
  from   ABC_LOCK_NAMED
  where  cmp_id = p_cmp_id
  and    lnm_id = p_lnm_id
  ;
end
